/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *vbox1;
  GtkWidget *hseparator1;
  GtkWidget *hbox1;
  GtkWidget *button1;
  GtkWidget *stop;
  GtkWidget *show;
  GtkWidget *hbox2;
  GtkWidget *entry1;
  GtkWidget *list1;
  GtkWidget *timer;
  GtkWidget *exit;
  GtkWidget *hbuttonbox1;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (window1), "window1", window1);
  gtk_window_set_title (GTK_WINDOW (window1), "window1");
  gtk_window_set_policy (GTK_WINDOW (window1), TRUE, TRUE, TRUE);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (window1), vbox1);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "hseparator1", hseparator1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox1), hseparator1, FALSE, FALSE, 0);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, TRUE, TRUE, 0);

  button1 = gtk_button_new_with_label ("S");
  gtk_widget_ref (button1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "button1", button1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button1);
  gtk_box_pack_start (GTK_BOX (hbox1), button1, FALSE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (button1, GTK_CAN_DEFAULT);
  gtk_button_set_relief (GTK_BUTTON (button1), GTK_RELIEF_HALF);

  stop = gtk_button_new_with_label ("P");
  gtk_widget_ref (stop);
  gtk_object_set_data_full (GTK_OBJECT (window1), "stop", stop,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (stop);
  gtk_box_pack_start (GTK_BOX (hbox1), stop, FALSE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (stop, GTK_CAN_DEFAULT);

  show = gtk_button_new_with_label ("S");
  gtk_widget_ref (show);
  gtk_object_set_data_full (GTK_OBJECT (window1), "show", show,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (show);
  gtk_box_pack_start (GTK_BOX (hbox1), show, FALSE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (show, GTK_CAN_DEFAULT);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (window1), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (hbox1), hbox2, FALSE, FALSE, 0);

  entry1 = gtk_entry_new ();
  gtk_widget_ref (entry1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "entry1", entry1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry1);
  gtk_box_pack_start (GTK_BOX (hbox2), entry1, FALSE, FALSE, 0);
  gtk_widget_set_usize (entry1, 70, 23);

  list1 = gtk_list_new ();
  gtk_widget_ref (list1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "list1", list1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (list1);
  gtk_box_pack_start (GTK_BOX (hbox1), list1, TRUE, FALSE, 0);

  timer = gtk_label_new ("timer");
  gtk_widget_ref (timer);
  gtk_object_set_data_full (GTK_OBJECT (window1), "timer", timer,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (timer);
  gtk_box_pack_start (GTK_BOX (hbox1), timer, FALSE, FALSE, 0);
  gtk_widget_set_usize (timer, -2, 33);
  gtk_misc_set_alignment (GTK_MISC (timer), 0, 1);
  gtk_misc_set_padding (GTK_MISC (timer), 0, 8);

  exit = gtk_button_new_with_label ("Q");
  gtk_widget_ref (exit);
  gtk_object_set_data_full (GTK_OBJECT (window1), "exit", exit,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (exit);
  gtk_box_pack_start (GTK_BOX (hbox1), exit, FALSE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (exit, GTK_CAN_DEFAULT);
  gtk_button_set_relief (GTK_BUTTON (exit), GTK_RELIEF_NONE);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "hbuttonbox1", hbuttonbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbuttonbox1, FALSE, TRUE, 0);

  gtk_signal_connect (GTK_OBJECT (button1), "clicked",
                      GTK_SIGNAL_FUNC (on_start_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (stop), "clicked",
                      GTK_SIGNAL_FUNC (on_stop_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (show), "clicked",
                      GTK_SIGNAL_FUNC (on_show_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (exit), "clicked",
                      GTK_SIGNAL_FUNC (gtk_main_quit),
                      NULL);

  return window1;
}

